# Generated by Django 2.1.2 on 2018-10-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('url', models.CharField(default=None, max_length=200)),
                ('avatar', models.ImageField(default=None, upload_to='attachments')),
            ],
        ),
    ]
