# Generated by Django 2.1.2 on 2018-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
