# Generated by Django 2.1.2 on 2018-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_proxy_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='avatar',
            field=models.ImageField(default=None, upload_to='attachments', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='channel_name',
            field=models.CharField(max_length=100, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='nickname',
            field=models.CharField(default=None, max_length=100, verbose_name='Ник канала'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='url',
            field=models.CharField(default=None, max_length=200, verbose_name='Ссылка'),
        ),
    ]
