# Generated by Django 2.1.2 on 2018-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20181012_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='button_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
