# Generated by Django 2.1.2 on 2018-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_proxy_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='button_url',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
