# Generated by Django 2.1.2 on 2018-10-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_auto_20181015_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='button_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
