# Generated by Django 2.1.2 on 2018-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_auto_20181015_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='button_url',
            field=models.URLField(),
        ),
    ]
