# Generated by Django 2.1.2 on 2018-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_auto_20181015_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='button_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
